# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ragas_annotator',
                'doc_host': 'https://explodinggradients.github.io',
                'git_url': 'https://github.com/explodinggradients/ragas_annotator',
                'lib_path': 'ragas_annotator'},
  'syms': {'ragas_annotator.core': {'ragas_annotator.core.foo': ('core.html#foo', 'ragas_annotator/core.py')}}}
