"""Use this class to represent the AI project that we are working on and to interact with datasets and experiments in it."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/project/core.ipynb.

# %% auto 0
__all__ = ['Project']

# %% ../../nbs/project/core.ipynb 4
import typing as t
import os
import asyncio

from fastcore.utils import patch

from ..backends.factory import RagasApiClientFactory
from ..backends.ragas_api_client import RagasApiClient
import ragas_annotator.typing as rt
from ..dataset import Dataset
from ..experiment import Experiment

# %% ../../nbs/project/core.ipynb 6
class Project:
    def _create_ragas_app_client(self):
        if ragas_app_client is None:
            self._ragas_app_client = RagasApiClientFactory.create()
        else:
            self._ragas_app_client = ragas_app_client

    def __init__(
        self,
        project_id: str,
        ragas_app_client: t.Optional[RagasApiClient] = None,
    ):
        self.project_id = project_id
        if ragas_app_client is None:
            self._ragas_app_client = RagasApiClientFactory.create()
        else:
            self._ragas_app_client = ragas_app_client

        # create the project
        try:
            existing_project = self._ragas_app_client.get_project_sync(id=self.project_id)
            self.project_id = existing_project["id"]
            self.name = existing_project["title"]
            self.description = existing_project["description"]
        except Exception as e:
            raise e

    @classmethod
    def create(
        cls,
        name: str,
        description: str = "",
        ragas_app_client: t.Optional[RagasApiClient] = None,
    ):
        ragas_app_client = RagasApiClientFactory.create()
        new_project = ragas_app_client.create_project_sync(title=name, description=description)
        return cls(new_project["id"], ragas_app_client)

    def __repr__(self):
        return f"Project(name='{self.name}')"

# %% ../../nbs/project/core.ipynb 10
@patch
def create_dataset(
    self: Project, model, name: t.Optional[str] = None
) -> Dataset:
    """Create a new dataset database.

    Args:
        name (str): Name of the dataset
        model (NotionModel): Model class defining the database structure

    Returns:
        Dataset: A new dataset object for managing entries
    """
    # Collect all properties from model fields
    properties = {}
    has_title = False
    for field_name, field in model._fields.items():
        properties.update(field._to_notion_property())
        if isinstance(field, nmt.Title):  # Check if we have a title field
            has_title = True

    if not has_title:
        raise ValueError(
            "In order to create a dataset, the model must have a nmt.Title field"
        )

    # Create the database
    if self.datasets_page_id == "":
        raise ValueError("Datasets page ID is not set")
    database_id = self._ragas_app_client.create_new_database(
        parent_page_id=self.datasets_page_id,
        title=name if name is not None else model.__name__,
        properties=properties,
    )

    # Return a new Dataset instance
    return Dataset(
        name=name if name is not None else model.__name__,
        model=model,
        database_id=database_id,
        notion_backend=self._ragas_app_client,
    )

# %% ../../nbs/project/core.ipynb 13
@patch
def get_dataset(self: Project, name: str, model) -> Dataset:
    """Get an existing dataset by name."""
    if self.datasets_page_id == "":
        raise ValueError("Datasets page ID is not set")

    # Search for database with given name
    database_id = self._ragas_app_client.get_database_id(
        parent_page_id=self.datasets_page_id, name=name, return_multiple=False
    )

    # For now, return Dataset without model type
    return Dataset(
        name=name,
        model=model,
        database_id=database_id,
        notion_backend=self._ragas_app_client,
    )
