"""Helps with testing `ragas_annotator` better."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/backends/mock_notion_client.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/backends/mock_notion_client.ipynb 2
import typing as t
import uuid
from copy import deepcopy
from datetime import datetime

from ..exceptions import NotFoundError
